config/routes.rb
require 'sidekiq/web'
JigsawRails::Application.routes.draw do
  resources :contacts

  resources :companies
  mount Sidekiq::Web, at: "/sidekiq"

  get '/driver/' => 'driver#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:jigsawid, :name, :website, :overview, :headquarters, :phone, :industries, :employees, :revenue, :ownership, :contacts)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:jigsawid, :company_id, :firstname, :lastname, :title, :city, :state, :zip)
    end
end

app/controllers/driver_controller.rb
require 'net/http'

class DriverController < ApplicationController
  include Breakbot
  include Jigsawhttp
  include Record

  def index
    render('index')
    break_bot_challenge()
    get_contacts
  end

  def get_contacts
    Company.where('contacts > ?', 1).each { |company| download_company_contacts(company.id) }
  end

  def get_companies
    newprocess = fork do
      (1..5399998).each do |id|
        CompaniesWorker.perform_async(id)
      end
    end
    Process.detach(newprocess)
  end

  def download_company_contacts(company_id)
    company = Company.find(company_id)
    company_record_ids = []
    #Requesting the number of records for your search
    record_count = harvest_number_of_records(request_page("/SearchContact.xhtml?companyId=#{company.jigsawid.to_s}&opCode=showCompDir", nil))
    page_count = get_number_of_pages(record_count)
    #Extracting #{record_count + 1} records from #{page_count} pages
    page_count.times do |num|
      page = num + 1
      #puts "Harvesting Record Numbers From Page: #{page}
      company_record_ids << harvest_record_ids(request_page("/SearchContact.xhtml?companyId=#{company.jigsawid.to_s}&opCode=paging&rpage=#{page}&rowsPerPage=50", nil))
    end
    #Downloading information from #{record_count + 1} individual records.  This may take a while
    company_record_ids.each do |page|
      page.each do |id|
        ContactsWorker.perform_async(company.jigsawid, id, company.id)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jigsawid %><br>
    <%= f.number_field :jigsawid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_area :overview %>
  </div>
  <div class="field">
    <%= f.label :headquarters %><br>
    <%= f.text_area :headquarters %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :industries %><br>
    <%= f.text_area :industries %>
  </div>
  <div class="field">
    <%= f.label :employees %><br>
    <%= f.text_field :employees %>
  </div>
  <div class="field">
    <%= f.label :revenue %><br>
    <%= f.text_field :revenue %>
  </div>
  <div class="field">
    <%= f.label :ownership %><br>
    <%= f.text_field :ownership %>
  </div>
  <div class="field">
    <%= f.label :contacts %><br>
    <%= f.number_field :contacts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Jigsawid</th>
      <th>Name</th>
      <th>Website</th>
      <th>Overview</th>
      <th>Headquarters</th>
      <th>Phone</th>
      <th>Industries</th>
      <th>Employees</th>
      <th>Revenue</th>
      <th>Ownership</th>
      <th>Contacts</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.jigsawid %></td>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.overview %></td>
        <td><%= company.headquarters %></td>
        <td><%= company.phone %></td>
        <td><%= company.industries %></td>
        <td><%= company.employees %></td>
        <td><%= company.revenue %></td>
        <td><%= company.ownership %></td>
        <td><%= company.contacts %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jigsawid:</strong>
  <%= @company.jigsawid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @company.overview %>
</p>

<p>
  <strong>Headquarters:</strong>
  <%= @company.headquarters %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Industries:</strong>
  <%= @company.industries %>
</p>

<p>
  <strong>Employees:</strong>
  <%= @company.employees %>
</p>

<p>
  <strong>Revenue:</strong>
  <%= @company.revenue %>
</p>

<p>
  <strong>Ownership:</strong>
  <%= @company.ownership %>
</p>

<p>
  <strong>Contacts:</strong>
  <%= @company.contacts %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jigsawid %><br>
    <%= f.number_field :jigsawid %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Jigsawid</th>
      <th>Company</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Title</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.jigsawid %></td>
        <td><%= contact.company_id %></td>
        <td><%= contact.firstname %></td>
        <td><%= contact.lastname %></td>
        <td><%= contact.title %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jigsawid:</strong>
  <%= @contact.jigsawid %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company_id %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @contact.title %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @contact.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contact.zip %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/driver/index.html.erb
<h1>Hello!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JigsawRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>